"""Independent point-in-time Indian cash-equity data foundation."""

__version__ = "0.1.0"

from .api import CompanyNameHistoryStore, DataPlatform, IsinHistoryStore, PriceStore, SecurityMaster, UniverseStore
from .profiles import (
    CANDIDATE_AUDIT_STATUS_VALUES,
    CANDIDATE_BOOLEAN_HARD_FAILURE_KEYS,
    CANDIDATE_DECISION_GATE_KEYS,
    CANDIDATE_DECISION_GATE_VALUES,
    CANDIDATE_DECISION_REQUIRED_FIELDS,
    CANDIDATE_FAIL_VALUE,
    CANDIDATE_FEATURE_READINESS_POLICY,
    CANDIDATE_GATE_PASS_INTERPRETATION,
    CANDIDATE_HARD_FAILURE_KEYS,
    CANDIDATE_NOT_RECORDED_VALUE,
    CANDIDATE_NUMERIC_HARD_FAILURE_KEYS,
    CANDIDATE_PASS_VALUE,
    CANDIDATE_PIT_UNIVERSE_INTERVAL_TYPE,
    CANDIDATE_PROMOTION_API_METHODS,
    CANDIDATE_PROMOTION_INTERPRETATION_VALUES,
    CANDIDATE_PROMOTION_SUMMARY_FIELDS,
    CANDIDATE_REFINED_BOUNDARY_SCAN_METHOD,
    CANDIDATE_RESEARCH_START_DATES,
)

__all__ = [
    "CANDIDATE_AUDIT_STATUS_VALUES",
    "CANDIDATE_BOOLEAN_HARD_FAILURE_KEYS",
    "CANDIDATE_DECISION_GATE_KEYS",
    "CANDIDATE_DECISION_GATE_VALUES",
    "CANDIDATE_DECISION_REQUIRED_FIELDS",
    "CANDIDATE_FAIL_VALUE",
    "CANDIDATE_FEATURE_READINESS_POLICY",
    "CANDIDATE_GATE_PASS_INTERPRETATION",
    "CANDIDATE_HARD_FAILURE_KEYS",
    "CANDIDATE_NOT_RECORDED_VALUE",
    "CANDIDATE_NUMERIC_HARD_FAILURE_KEYS",
    "CANDIDATE_PASS_VALUE",
    "CANDIDATE_PIT_UNIVERSE_INTERVAL_TYPE",
    "CANDIDATE_PROMOTION_API_METHODS",
    "CANDIDATE_PROMOTION_INTERPRETATION_VALUES",
    "CANDIDATE_PROMOTION_SUMMARY_FIELDS",
    "CANDIDATE_REFINED_BOUNDARY_SCAN_METHOD",
    "CANDIDATE_RESEARCH_START_DATES",
    "CompanyNameHistoryStore",
    "DataPlatform",
    "IsinHistoryStore",
    "SecurityMaster",
    "PriceStore",
    "UniverseStore",
]
